### ISSUE TITLE
"ModuleNotFoundError: No module named 'wx' " while trying to run dspdemo.py

### ISSUE THREAD

**Issue by SuganthanBC** [belangeo/dspdemo#1]
I cloned this repo, opened command prompt in windows and tried to run
```
py -3.7 dspdemo.py
```

and I got the following error message:

```
Traceback (most recent call last):
  File "dspdemo.py", line 1, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
```

I have installed Python 3.7 and [Pyo ](https://github.com/belangeo/pyo) using the appropriate commands. I am a beginner in Python, am I missing something obvious?

PS: I have tried the DSP Demo installer found in the [release](https://github.com/belangeo/dspdemo/releases/tag/0.2.0). After installation, running the standalone DSPDemo.exe quits without a message.

**Comment by belangeo** [comment]
You can install wxpython with the command:

py -3.7 -m pip install wxPython 

Be aware that DSPDemo is a fairly dead project, I don’t intend to update it anymore in the future…
